############################################
# boonstra@netapp.com / 2020
# global/private vars are in vars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  name: Setup ONTAP
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    volname: "{{ volname }}"
    vserver: "{{ vserver }}"
    aggrname: " {{ aggrname }}"
    state: "{{ state }}"
  tasks:
  - name: Change volume size
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ new_size }}"
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ volname }}"
      space_guarantee: "none"
      volume_security_style: unix
      vserver: "{{ vserver }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
