############################################
# boonstra@netapp.com / 2021
# global/private vars are in vars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  collections:
    - netapp.ontap
    - netapp.um_info
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  tasks:
  - name: Create volume 
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ comment }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ new_size }}"
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ comment }}"
      space_guarantee: "none"
      volume_security_style: unix
      comment: "{{ comment }}"
      vserver: "{{ vserver }}"
      <<: *login
