---
- hosts: localhost
  name: Setup ONTAP
  vars_files:
   vars.yml
  vars:
  tasks:
  - name: Get facts
    na_ontap_command:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
#     command: ['node', 'show', '-fields', 'node,health,uptime,model']
      command: ['vserver nfs modify -vserver "{{ vserver }}" -ntfs-unix-security-ops ignore']
      privilege: 'admin'
      return_dict: true
